# Sorting and cleaning 
---



In order to effectively analyse a dataset, often we need to prepare it first. 
Before a dataset is ready to be analysed we might need to:  

* sort the data (can be a series or dataframe)  
* remove any NaN values or drop NA values   
* remove duplicate records (identical rows)  
* normalise data in dataframe columns so that has a common scale [reference](https://towardsai.net/p/data-science/how-when-and-why-should-you-normalize-standardize-rescale-your-data-3f083def38ff#:~:text=Similarly%2C%20the%20goal%20of%20normalization,dataset%20does%20not%20require%20normalization.&text=So%20we%20normalize%20the%20data,variables%20to%20the%20same%20range.)

## Sorting the data  
---


Typically we want to sort data by the values in one or more columns in the dataframe  

To sort the dataframe by series we use the pandas function **sort_values()**.  

By default `sort_values()` sorts into ascending order.

* sort by a single column e.g.
  * `df.sort_values("Make") `
* sort by multiple columns e.g. 
  * `df.sort_values(by = ["Model", "Make"]) `
    * this sorts by Model, then my Make 
* sort in *descending* order
  * `df.sort_values(by = "Make", ascending = False)`
  * `df.sort_values(by = ["Make", "Model"], ascending = False])`  

Dataframes are mostly immutable, changes like sort_values do not change the dataframe permanently, they just change it for the time that the instruction is being used.

`df.sort_values(by='Make')` *dataframe is now in sorted order and can be copied to a new dataframe*  
`df` *original dataframe, df, will be as it was - unsorted* 

To split the dataframe after sorting, do this in the same instruction, e.g.:

`df.sort_values(by = ["Make", "Model"], ascending = False])[["Make", "Model"]]`

This sorts on Make and then Model in descending order, then splits off the Make and Model columns.

`df.sort_values(by = ["Make", "Model"], ascending = False])[["Make", "Model"]].head()`

This sorts on Make and then Model, then splits off the Make and Model columns and then splits off the first 5 rows.

### Exercise 1 - get data, sort by happiness score 
---

Read data from the Excel file on Happiness Data at this link: https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true

Display first 5 rows of data  

The data is currently sorted by Happiness Rank...
*  sort the data by Happiness Score in ascending order
*  display sorted table

**Test output**:  
The lowest score (displayed first) is 2.839, Togo  
The highest score (displayed last) is 7.587, Switzerland

In [104]:
import pandas as pd

url = "https://github.com/futureCodersSE/working-with-data/blob/main/Happiness-Data/2015.xlsx?raw=true"

happiness_df = pd.read_excel(url)

# Display first 5 rows
display(happiness_df.head())

# Display table sorted by Happiness Score
display(happiness_df.sort_values("Happiness Score"))

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
154,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
153,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
152,Afghanistan,Southern Asia,153,3.575,0.03084,0.31982,0.30285,0.30335,0.23414,0.09719,0.36510,1.95210
151,Burkina Faso,Sub-Saharan Africa,152,3.587,0.04324,0.25812,0.85188,0.27125,0.39493,0.12832,0.21747,1.46494
150,Ivory Coast,Sub-Saharan Africa,151,3.655,0.05141,0.46534,0.77115,0.15185,0.46866,0.17922,0.20165,1.41723
149,Guinea,Sub-Saharan Africa,150,3.656,0.03590,0.17417,0.46475,0.24009,0.37725,0.12139,0.28657,1.99172
148,Chad,Sub-Saharan Africa,149,3.667,0.03830,0.34193,0.76062,0.15010,0.23501,0.05269,0.18386,1.94296
147,Central African Republic,Sub-Saharan Africa,148,3.678,0.06112,0.07850,0.00000,0.06699,0.48879,0.08289,0.23835,2.72230
146,Madagascar,Sub-Saharan Africa,147,3.681,0.03633,0.20824,0.66801,0.46721,0.19184,0.08124,0.21333,1.85100
145,Tanzania,Sub-Saharan Africa,146,3.781,0.05061,0.28520,1.00268,0.38215,0.32878,0.05747,0.34377,1.38079
144,Cambodia,Southeastern Asia,145,3.819,0.05069,0.46038,0.62736,0.61114,0.66246,0.07247,0.40359,0.98195
143,Niger,Sub-Saharan Africa,144,3.845,0.03602,0.06940,0.77265,0.29707,0.47692,0.15639,0.19387,1.87877
142,Gabon,Sub-Saharan Africa,143,3.896,0.04547,1.06024,0.90528,0.43372,0.31914,0.11091,0.06822,0.99895
141,Senegal,Sub-Saharan Africa,142,3.904,0.03608,0.36498,0.97619,0.43540,0.36772,0.10713,0.20843,1.44395
140,Uganda,Sub-Saharan Africa,141,3.931,0.04317,0.21102,1.13299,0.33861,0.45727,0.07267,0.29066,1.42766
139,Comoros,Sub-Saharan Africa,140,3.956,0.04797,0.23906,0.79273,0.36315,0.22917,0.19900,0.17441,1.95812
138,Congo (Brazzaville),Sub-Saharan Africa,139,3.989,0.06682,0.67866,0.66290,0.31051,0.41466,0.11686,0.12388,1.68135
137,Mali,Sub-Saharan Africa,138,3.995,0.05602,0.26074,1.03526,0.20583,0.38857,0.12352,0.18798,1.79293
136,Angola,Sub-Saharan Africa,137,4.033,0.04758,0.75778,0.86040,0.16683,0.10384,0.07122,0.12344,1.94939
135,Yemen,Middle East and Northern Africa,136,4.077,0.04367,0.54649,0.68093,0.40064,0.35571,0.07854,0.09131,1.92313
134,Egypt,Middle East and Northern Africa,135,4.194,0.03260,0.88180,0.74700,0.61712,0.17288,0.06324,0.11291,1.59927
133,Bulgaria,Central and Eastern Europe,134,4.218,0.04828,1.01216,1.10614,0.76649,0.30587,0.00872,0.11921,0.89991
132,Cameroon,Sub-Saharan Africa,133,4.252,0.04678,0.42250,0.88767,0.23402,0.49309,0.05786,0.20618,1.95071
131,Sri Lanka,Southern Asia,132,4.271,0.03751,0.83524,1.01905,0.70806,0.53726,0.09179,0.40828,0.67108
130,Malawi,Sub-Saharan Africa,131,4.292,0.06130,0.01604,0.41134,0.22562,0.43054,0.06977,0.33128,2.80791
129,Georgia,Central and Eastern Europe,130,4.297,0.04221,0.74190,0.38562,0.72926,0.40577,0.38331,0.05547,1.59541
128,Myanmar,Southeastern Asia,129,4.307,0.04351,0.27108,0.70905,0.48246,0.44017,0.19034,0.79588,1.41805
127,Botswana,Sub-Saharan Africa,128,4.332,0.04934,0.99355,1.10464,0.04776,0.49495,0.12474,0.10461,1.46181
126,Armenia,Central and Eastern Europe,127,4.350,0.04763,0.76821,0.77711,0.72990,0.19847,0.03900,0.07855,1.75873
125,Djibouti,Sub-Saharan Africa,126,4.369,0.08096,0.44025,0.59207,0.36291,0.46074,0.28105,0.18093,2.05125
124,Kenya,Sub-Saharan Africa,125,4.419,0.04734,0.36471,0.99876,0.41435,0.42215,0.05839,0.37542,1.78555
123,Mauritania,Sub-Saharan Africa,124,4.436,0.03947,0.45407,0.86908,0.35874,0.24232,0.17461,0.21900,2.11773
122,Sierra Leone,Sub-Saharan Africa,123,4.507,0.07068,0.33024,0.95571,0.00000,0.40840,0.08786,0.21488,2.51009
121,Ethiopia,Sub-Saharan Africa,122,4.512,0.03780,0.19073,0.60406,0.44055,0.43450,0.15048,0.24325,2.44876
120,Nepal,Southern Asia,121,4.514,0.03607,0.35997,0.86449,0.56874,0.38282,0.05907,0.32296,1.95637
119,Congo (Kinshasa),Sub-Saharan Africa,120,4.517,0.03680,0.00000,1.00120,0.09806,0.22605,0.07625,0.24834,2.86712
118,Haiti,Latin America and Caribbean,119,4.518,0.07331,0.26673,0.74302,0.38847,0.24425,0.17175,0.46187,2.24173
117,Sudan,Sub-Saharan Africa,118,4.550,0.06740,0.52107,1.01404,0.36878,0.10081,0.14660,0.19062,2.20857
116,India,Southern Asia,117,4.565,0.02043,0.64499,0.38174,0.51529,0.39786,0.08492,0.26475,2.27513
115,Liberia,Sub-Saharan Africa,116,4.571,0.11068,0.07120,0.78968,0.34201,0.28531,0.06232,0.24362,2.77729
114,Zimbabwe,Sub-Saharan Africa,115,4.610,0.04290,0.27100,1.03276,0.33475,0.25861,0.08079,0.18987,2.44191
113,Ghana,Sub-Saharan Africa,114,4.633,0.04742,0.54558,0.67954,0.40132,0.42342,0.04355,0.23087,2.30919
112,South Africa,Sub-Saharan Africa,113,4.642,0.04585,0.92049,1.18468,0.27688,0.33207,0.08884,0.11973,1.71956
111,Iraq,Middle East and Northern Africa,112,4.677,0.05232,0.98549,0.81889,0.60237,0.00000,0.13788,0.17922,1.95335
110,Ukraine,Central and Eastern Europe,111,4.681,0.04412,0.79907,1.20278,0.67390,0.25123,0.02961,0.15275,1.57140
109,Iran,Middle East and Northern Africa,110,4.686,0.04449,1.00880,0.54447,0.69805,0.30033,0.05863,0.38086,1.69440
108,Bangladesh,Southern Asia,109,4.694,0.03077,0.39753,0.43106,0.60164,0.40820,0.12569,0.21222,2.51767
107,Palestinian Territories,Middle East and Northern Africa,108,4.715,0.04394,0.59867,0.92558,0.66015,0.24499,0.12905,0.11251,2.04384
106,Tunisia,Middle East and Northern Africa,107,4.739,0.03589,0.88113,0.60429,0.73793,0.26268,0.06358,0.06431,2.12466
105,Tajikistan,Central and Eastern Europe,106,4.786,0.03198,0.39047,0.85563,0.57379,0.47216,0.15072,0.22974,2.11399
104,Honduras,Latin America and Caribbean,105,4.788,0.05648,0.59532,0.95348,0.69510,0.40148,0.06825,0.23027,1.84408
103,Hungary,Central and Eastern Europe,104,4.800,0.06107,1.12094,1.20215,0.75905,0.32112,0.02758,0.12800,1.24074
102,Lebanon,Middle East and Northern Africa,103,4.839,0.04337,1.02564,0.80001,0.83947,0.33916,0.04582,0.21854,1.57059
101,Greece,Western Europe,102,4.857,0.05062,1.15406,0.92933,0.88213,0.07699,0.01397,0.00000,1.80101
100,Swaziland,Sub-Saharan Africa,101,4.867,0.08742,0.71206,1.07284,0.07566,0.30658,0.03060,0.18259,2.48676
99,Mongolia,Eastern Asia,100,4.874,0.03313,0.82819,1.30060,0.60268,0.43626,0.02666,0.33230,1.34759
98,Laos,Southeastern Asia,99,4.876,0.06698,0.59066,0.73803,0.54909,0.59591,0.24249,0.42192,1.73799
97,Dominican Republic,Latin America and Caribbean,98,4.885,0.07446,0.89537,1.17202,0.66825,0.57672,0.14234,0.21684,1.21305
96,Lesotho,Sub-Saharan Africa,97,4.898,0.09438,0.37545,1.04103,0.07612,0.31767,0.12504,0.16388,2.79832
95,Bosnia and Herzegovina,Central and Eastern Europe,96,4.949,0.06913,0.83223,0.91916,0.79081,0.09245,0.00227,0.24808,2.06367
94,Albania,Central and Eastern Europe,95,4.959,0.05013,0.87867,0.80434,0.81325,0.35733,0.06413,0.14272,1.89894
93,Mozambique,Sub-Saharan Africa,94,4.971,0.07896,0.08308,1.02626,0.09131,0.34037,0.15603,0.22269,3.05137
92,Macedonia,Central and Eastern Europe,93,5.007,0.05376,0.91851,1.00232,0.73545,0.33457,0.05327,0.22359,1.73933
91,Morocco,Middle East and Northern Africa,92,5.013,0.03420,0.73479,0.64095,0.60954,0.41691,0.08546,0.07172,2.45373
90,Somaliland region,Sub-Saharan Africa,91,5.057,0.06161,0.18847,0.95152,0.43873,0.46582,0.39928,0.50318,2.11032
89,Philippines,Southeastern Asia,90,5.073,0.04934,0.70532,1.03516,0.58114,0.62545,0.12279,0.24991,1.75360
88,Latvia,Central and Eastern Europe,89,5.098,0.04640,1.11312,1.09562,0.72437,0.29671,0.06332,0.18226,1.62215
87,Portugal,Western Europe,88,5.102,0.04802,1.15991,1.13935,0.87519,0.51469,0.01078,0.13719,1.26462
86,Serbia,Central and Eastern Europe,87,5.123,0.04864,0.92053,1.00964,0.74836,0.20107,0.02617,0.19231,2.02500
85,Romania,Central and Eastern Europe,86,5.124,0.06607,1.04345,0.88588,0.76890,0.35068,0.00649,0.13748,1.93129
84,Zambia,Sub-Saharan Africa,85,5.129,0.06988,0.47038,0.91612,0.29924,0.48827,0.12468,0.19591,2.63430
83,China,Eastern Asia,84,5.140,0.02424,0.89012,0.94675,0.81658,0.51697,0.02781,0.08185,1.86040
82,Montenegro,Central and Eastern Europe,82,5.192,0.05235,0.97438,0.90557,0.72521,0.18260,0.14296,0.16140,2.10017
81,Jordan,Middle East and Northern Africa,82,5.192,0.04524,0.90198,1.05392,0.69639,0.40661,0.14293,0.11053,1.87996
80,Pakistan,Southern Asia,81,5.194,0.03726,0.59543,0.41411,0.51466,0.12102,0.10464,0.33671,3.10709
79,Azerbaijan,Central and Eastern Europe,80,5.212,0.03363,1.02389,0.93793,0.64045,0.37030,0.16065,0.07799,2.00073
78,Bhutan,Southern Asia,79,5.253,0.03225,0.77042,1.10395,0.57407,0.53206,0.15445,0.47998,1.63794
77,Nigeria,Sub-Saharan Africa,78,5.268,0.04192,0.65435,0.90432,0.16007,0.34334,0.04030,0.27233,2.89319
76,Kyrgyzstan,Central and Eastern Europe,77,5.286,0.03823,0.47428,1.15115,0.65088,0.43477,0.04232,0.30030,2.23270
75,Turkey,Middle East and Northern Africa,76,5.332,0.03864,1.06098,0.94632,0.73172,0.22815,0.15746,0.12253,2.08528
74,Vietnam,Southeastern Asia,75,5.360,0.03107,0.63216,0.91226,0.74676,0.59444,0.10441,0.16860,2.20173
73,Indonesia,Southeastern Asia,74,5.399,0.02596,0.82827,1.08708,0.63793,0.46611,0.00000,0.51535,1.86399
72,Estonia,Central and Eastern Europe,73,5.429,0.04013,1.15174,1.22791,0.77361,0.44888,0.15184,0.08680,1.58782
71,Hong Kong,Eastern Asia,72,5.474,0.05051,1.38604,1.05818,1.01328,0.59608,0.37124,0.39478,0.65429
70,Mauritius,Sub-Saharan Africa,71,5.477,0.07197,1.00761,0.98521,0.70950,0.56066,0.07521,0.37744,1.76145
69,Turkmenistan,Central and Eastern Europe,70,5.548,0.04175,0.95847,1.22668,0.53886,0.47610,0.30844,0.16979,1.86984
68,Kosovo,Central and Eastern Europe,69,5.589,0.05018,0.80148,0.81198,0.63132,0.24749,0.04741,0.28310,2.76579
67,Algeria,Middle East and Northern Africa,68,5.605,0.05099,0.93929,1.07772,0.61766,0.28579,0.17383,0.07822,2.43209
66,Cyprus,Western Europe,67,5.689,0.05580,1.20813,0.89318,0.92356,0.40672,0.06146,0.30638,1.88931
65,North Cyprus,Western Europe,66,5.695,0.05635,1.20806,1.07008,0.92356,0.49027,0.14280,0.26169,1.59888
64,Jamaica,Latin America and Caribbean,65,5.709,0.13693,0.81038,1.15102,0.68741,0.50442,0.02299,0.21230,2.32038
63,Russia,Central and Eastern Europe,64,5.716,0.03135,1.13764,1.23617,0.66926,0.36679,0.03005,0.00199,2.27394
62,Libya,Middle East and Northern Africa,63,5.754,0.07832,1.13145,1.11862,0.70380,0.41668,0.11023,0.18295,2.09066
61,Croatia,Central and Eastern Europe,62,5.759,0.04394,1.08254,0.79624,0.78805,0.25883,0.02430,0.05444,2.75414
60,Malaysia,Southeastern Asia,61,5.770,0.04330,1.12486,1.07023,0.72394,0.53024,0.10501,0.33075,1.88541
59,Poland,Central and Eastern Europe,60,5.791,0.04263,1.12555,1.27948,0.77903,0.53122,0.04212,0.16759,1.86565
58,Belarus,Central and Eastern Europe,59,5.813,0.03938,1.03192,1.23289,0.73608,0.37938,0.19090,0.11046,2.13090
57,Peru,Latin America and Caribbean,58,5.824,0.04615,0.90019,0.97459,0.73017,0.41496,0.05989,0.14982,2.59450
56,Nicaragua,Latin America and Caribbean,57,5.828,0.05371,0.59325,1.14184,0.74314,0.55475,0.19317,0.27815,2.32407
55,Lithuania,Central and Eastern Europe,56,5.833,0.03843,1.14723,1.25745,0.73128,0.21342,0.01031,0.02641,2.44649
54,Slovenia,Central and Eastern Europe,55,5.848,0.04251,1.18498,1.27385,0.87337,0.60855,0.03787,0.25328,1.61583
53,Kazakhstan,Central and Eastern Europe,54,5.855,0.04114,1.12254,1.12241,0.64368,0.51649,0.08454,0.11827,2.24729
52,Paraguay,Latin America and Caribbean,53,5.878,0.04563,0.75985,1.30477,0.66098,0.53899,0.08242,0.34240,2.18896
51,Moldova,Central and Eastern Europe,52,5.889,0.03799,0.59448,1.01528,0.61826,0.32818,0.01615,0.20951,3.10712
50,Bolivia,Latin America and Caribbean,51,5.890,0.05642,0.68133,0.97841,0.53920,0.57414,0.08800,0.20536,2.82334
49,Italy,Western Europe,50,5.948,0.03914,1.25114,1.19777,0.95446,0.26236,0.02901,0.22823,2.02518
48,Bahrain,Middle East and Northern Africa,49,5.960,0.05412,1.32376,1.21624,0.74716,0.45492,0.30600,0.17362,1.73797
47,Ecuador,Latin America and Caribbean,48,5.975,0.04528,0.86402,0.99903,0.79075,0.48574,0.18090,0.11541,2.53942
46,South Korea,Eastern Asia,47,5.984,0.04098,1.24461,0.95774,0.96538,0.33208,0.07857,0.18557,2.21978
45,Japan,Eastern Asia,46,5.987,0.03581,1.27074,1.25712,0.99111,0.49615,0.18060,0.10705,1.68435
44,Slovakia,Central and Eastern Europe,45,5.995,0.04267,1.16891,1.26999,0.78902,0.31751,0.03431,0.16893,2.24639
43,Uzbekistan,Central and Eastern Europe,44,6.003,0.04361,0.63244,1.34043,0.59772,0.65821,0.30826,0.22837,2.23741
42,Guatemala,Latin America and Caribbean,43,6.123,0.05224,0.74553,1.04356,0.64425,0.57733,0.09472,0.27489,2.74255
41,El Salvador,Latin America and Caribbean,42,6.130,0.05618,0.76454,1.02507,0.67737,0.40350,0.11776,0.10692,3.03500
40,Trinidad and Tobago,Latin America and Caribbean,41,6.168,0.10895,1.21183,1.18354,0.61483,0.55884,0.01140,0.31844,2.26882
39,Suriname,Latin America and Caribbean,40,6.269,0.09811,0.99534,0.97200,0.60820,0.59657,0.13633,0.16991,2.79094
38,Kuwait,Middle East and Northern Africa,39,6.295,0.04456,1.55422,1.16594,0.72492,0.55499,0.25609,0.16228,1.87634
37,Taiwan,Eastern Asia,38,6.298,0.03868,1.29098,1.07617,0.87530,0.39740,0.08129,0.25376,2.32323
36,Malta,Western Europe,37,6.302,0.04206,1.20740,1.30203,0.88721,0.60365,0.13586,0.51752,1.64880
35,Spain,Western Europe,36,6.329,0.03468,1.23011,1.31379,0.95562,0.45951,0.06398,0.18227,2.12367
34,Saudi Arabia,Middle East and Northern Africa,35,6.411,0.04633,1.39541,1.08393,0.72025,0.31048,0.32524,0.13706,2.43872
33,Thailand,Southeastern Asia,34,6.455,0.03557,0.96690,1.26504,0.73850,0.55664,0.03187,0.57630,2.31945
32,Colombia,Latin America and Caribbean,33,6.477,0.05051,0.91861,1.24018,0.69077,0.53466,0.05120,0.18401,2.85737
31,Uruguay,Latin America and Caribbean,32,6.485,0.04539,1.06166,1.20890,0.81160,0.60362,0.24558,0.23240,2.32142
30,Czech Republic,Central and Eastern Europe,31,6.505,0.04168,1.17898,1.20643,0.84483,0.46364,0.02652,0.10686,2.67782
29,Argentina,Latin America and Caribbean,30,6.574,0.04612,1.05351,1.24823,0.78723,0.44974,0.08484,0.11451,2.83600
28,France,Western Europe,29,6.575,0.03512,1.27778,1.26038,0.94579,0.55011,0.20646,0.12332,2.21126
27,Qatar,Middle East and Northern Africa,28,6.611,0.06257,1.69042,1.07860,0.79733,0.64040,0.52208,0.32573,1.55674
26,Chile,Latin America and Caribbean,27,6.670,0.05800,1.10715,1.12447,0.85857,0.44132,0.12869,0.33363,2.67585
25,Germany,Western Europe,26,6.750,0.01848,1.32792,1.29937,0.89186,0.61477,0.21843,0.28214,2.11569
24,Panama,Latin America and Caribbean,25,6.786,0.04910,1.06353,1.19850,0.79661,0.54210,0.09270,0.24434,2.84848
23,Singapore,Southeastern Asia,24,6.798,0.03780,1.52186,1.02000,1.02525,0.54252,0.49210,0.31105,1.88501
22,Venezuela,Latin America and Caribbean,23,6.810,0.06476,1.04424,1.25596,0.72052,0.42908,0.11069,0.05841,3.19131
21,Oman,Middle East and Northern Africa,22,6.853,0.05335,1.36011,1.08182,0.76276,0.63274,0.32524,0.21542,2.47489
20,United Kingdom,Western Europe,21,6.867,0.01866,1.26637,1.28548,0.90943,0.59625,0.32067,0.51912,1.96994
19,United Arab Emirates,Middle East and Northern Africa,20,6.901,0.03729,1.42727,1.12575,0.80925,0.64157,0.38583,0.26428,2.24743
18,Belgium,Western Europe,19,6.937,0.03595,1.30782,1.28566,0.89667,0.58450,0.22540,0.22250,2.41484
17,Ireland,Western Europe,18,6.940,0.03676,1.33596,1.36948,0.89533,0.61777,0.28703,0.45901,1.97570
16,Luxembourg,Western Europe,17,6.946,0.03499,1.56391,1.21963,0.91894,0.61583,0.37798,0.28034,1.96961
15,Brazil,Latin America and Caribbean,16,6.983,0.04076,0.98124,1.23287,0.69702,0.49049,0.17521,0.14574,3.26001
14,United States,North America,15,7.119,0.03839,1.39451,1.24711,0.86179,0.54604,0.15890,0.40105,2.51011
13,Mexico,Latin America and Caribbean,14,7.187,0.04176,1.02054,0.91451,0.81444,0.48181,0.21312,0.14074,3.60214
12,Austria,Western Europe,13,7.200,0.03751,1.33723,1.29704,0.89042,0.62433,0.18676,0.33088,2.53320
11,Costa Rica,Latin America and Caribbean,12,7.226,0.04454,0.95578,1.23788,0.86027,0.63376,0.10583,0.25497,3.17728
10,Israel,Middle East and Northern Africa,11,7.278,0.03470,1.22857,1.22393,0.91387,0.41319,0.07785,0.33172,3.08854
9,Australia,Australia and New Zealand,10,7.284,0.04083,1.33358,1.30923,0.93156,0.65124,0.35637,0.43562,2.26646
8,New Zealand,Australia and New Zealand,9,7.286,0.03371,1.25018,1.31967,0.90837,0.63938,0.42922,0.47501,2.26425
7,Sweden,Western Europe,8,7.364,0.03157,1.33171,1.28907,0.91087,0.65980,0.43844,0.36262,2.37119
6,Netherlands,Western Europe,7,7.378,0.02799,1.32944,1.28017,0.89284,0.61576,0.31814,0.47610,2.46570
5,Finland,Western Europe,6,7.406,0.03140,1.29025,1.31826,0.88911,0.64169,0.41372,0.23351,2.61955
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738

### Exercise 2 - sort by multiple columns, display the first 5 rows 
---

1. sort the data by Economy (GDP per Capita) and Health (Life Expectancy) in ascending order 
2. display the first 5 rows of sorted data 

**Test output**:  
Records 122, 127, 147, 100, 96

In [105]:
# This sorts by Life Expectancy, then by GDP per Capita, producing the outcome above
display(happiness_df.sort_values(["Health (Life Expectancy)", "Economy (GDP per Capita)"]).head())

# This sorts by GDP per Capita, then by Life Expectancy
display(happiness_df.sort_values(["Economy (GDP per Capita)", "Health (Life Expectancy)"]).head())

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
122,Sierra Leone,Sub-Saharan Africa,123,4.507,0.07068,0.33024,0.95571,0.00000,0.40840,0.08786,0.21488,2.51009
127,Botswana,Sub-Saharan Africa,128,4.332,0.04934,0.99355,1.10464,0.04776,0.49495,0.12474,0.10461,1.46181
147,Central African Republic,Sub-Saharan Africa,148,3.678,0.06112,0.07850,0.00000,0.06699,0.48879,0.08289,0.23835,2.72230
100,Swaziland,Sub-Saharan Africa,101,4.867,0.08742,0.71206,1.07284,0.07566,0.30658,0.03060,0.18259,2.48676
96,Lesotho,Sub-Saharan Africa,97,4.898,0.09438,0.37545,1.04103,0.07612,0.31767,0.12504,0.16388,2.79832

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
119,Congo (Kinshasa),Sub-Saharan Africa,120,4.517,0.03680,0.00000,1.00120,0.09806,0.22605,0.07625,0.24834,2.86712
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
130,Malawi,Sub-Saharan Africa,131,4.292,0.06130,0.01604,0.41134,0.22562,0.43054,0.06977,0.33128,2.80791
143,Niger,Sub-Saharan Africa,144,3.845,0.03602,0.06940,0.77265,0.29707,0.47692,0.15639,0.19387,1.87877
115,Liberia,Sub-Saharan Africa,116,4.571,0.11068,0.07120,0.78968,0.34201,0.28531,0.06232,0.24362,2.77729

### Exercise 3 - sorting in descending order 
---
 
Sort the data by Freedom and Trust (Government Corruption) in descending order and show the Country and Region only for the last five rows

**Test output**:
136, 117, 95, 101, 111 Country and Region columns

In [106]:
display(happiness_df.sort_values(by = ["Freedom", "Trust (Government Corruption)"], ascending = False).tail())

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
136,Angola,Sub-Saharan Africa,137,4.033,0.04758,0.75778,0.86040,0.16683,0.10384,0.07122,0.12344,1.94939
117,Sudan,Sub-Saharan Africa,118,4.550,0.06740,0.52107,1.01404,0.36878,0.10081,0.14660,0.19062,2.20857
95,Bosnia and Herzegovina,Central and Eastern Europe,96,4.949,0.06913,0.83223,0.91916,0.79081,0.09245,0.00227,0.24808,2.06367
101,Greece,Western Europe,102,4.857,0.05062,1.15406,0.92933,0.88213,0.07699,0.01397,0.00000,1.80101
111,Iraq,Middle East and Northern Africa,112,4.677,0.05232,0.98549,0.81889,0.60237,0.00000,0.13788,0.17922,1.95335

# Cleaning the data

Data comes from a range of sources:  forms, monitoring devices, etc.  There will often be missing values, duplicate records and values that are incorrectly formatted.  These can affect summary statistics and graphs plotted from the data.

Techniques for data cleansing include:
*  removing records with missing or null data (NaN, NA, "")
*  removing duplicate rows (keeping just one, either the first or the last)

Removal of rows according to criteria, or of columns are other ways that data might be cleaned up.

---

## Removing NaN/Dropping NA values 

pandas have functions for checking a dataframe, or column, for null values, checking a column for missing values, and functions for dropping all rows that contain null values.

* check for NA/NaN/missing values across dataframe (returns True if NA values exist)  
  `df.isnull().values.any()`  

* check for NA/NaN/missing values in specific column  
  `df["Make"].isnull().values.any()`  

* drop all rows that have NA/NaN values   
  `df.dropna()`  

* drop rows where NA/NaN values exist in specific columns  
  `df.dropna(subset = ["Make", "Model"])`

### Exercise 4 - check for null values 
---

1. read data from the file housing_in_london_yearly_variables.csv from this link: https://raw.githubusercontent.com/futureCodersSE/working-with-data/main/Data%20sets/housing_in_london_yearly_variables.csv 
2. check if any NA values exist in the dataframe and print the result 
3. use df.info() to see which columns have null entries (*Hint: if the non-null count is less than total entries, column contains missing/NA entries*)  

**Test output**:
True
.info shows median_salary, life_satisfaction, recycling_pct, population_size, number_of_jobs, area_size, no_of_houses all less than total rows (1071)

In [107]:
import pandas as pd

url = "https://raw.githubusercontent.com/futureCodersSE/working-with-data/main/Data%20sets/housing_in_london_yearly_variables.csv"

housing_df = pd.read_csv(url)

# Check if there are null values in the dataframe
print(housing_df.isnull().values.any())

# Display info to find columns with less that total rows
display(housing_df.info())

True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1071 entries, 0 to 1070
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   code               1071 non-null   object
 1   area               1071 non-null   object
 2   date               1071 non-null   object
 3   median_salary      1049 non-null   float64
 4   life_satisfaction  352 non-null    float64
 5   mean_salary        1071 non-null   object
 6   recycling_pct      860 non-null    object
 7   population_size    1018 non-null   float64
 8   number_of_jobs     931 non-null    float64
 9   area_size          666 non-null    float64
 10  no_of_houses       666 non-null    float64
 11  borough_flag       1071 non-null   int64
dtypes: float64(6), int64(1), object(5)
memory usage: 100.5+ KB

None

### Exercise 5 - remove null values 
---

1. remove rows with NA values for `life_satisfaction` (use [ ] even if only one column in list)
2. remove all NA values across whole dataframe 

**Test output**:  
1.  Row count reduced to 352 rows
2.  Row count reduced to 267 rows

In [108]:
display(housing_df.dropna(subset = ["life_satisfaction"]))

display(housing_df.dropna())

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
613,E09000002,barking and dagenham,2011-12-01,28201.0,7.05,33568,30,187029.0,54000.0,3780.0,71079.0,1
614,E09000003,barnet,2011-12-01,30237.0,7.43,33062,34,357538.0,147000.0,8675.0,139346.0,1
615,E09000004,bexley,2011-12-01,28638.0,7.42,31812,54,232774.0,78000.0,6429.0,95037.0,1
616,E09000005,brent,2011-12-01,26772.0,7.11,29609,37,312245.0,115000.0,4323.0,112083.0,1
617,E09000006,bromley,2011-12-01,28163.0,7.50,32863,50,310554.0,119000.0,15013.0,135036.0,1
618,E09000007,camden,2011-12-01,35967.0,7.25,45588,33,220087.0,331000.0,2179.0,99828.0,1
619,E09000008,croydon,2011-12-01,28979.0,7.04,33050,38,364815.0,136000.0,8650.0,148099.0,1
620,E09000009,ealing,2011-12-01,28646.0,7.22,34725,41,339314.0,148000.0,5554.0,127187.0,1
621,E09000010,enfield,2011-12-01,26412.0,7.23,31797,35,313935.0,110000.0,8220.0,122042.0,1
622,E09000011,greenwich,2011-12-01,29932.0,7.18,32581,39,255483.0,81000.0,5044.0,103186.0,1
623,E09000012,hackney,2011-12-01,33512.0,7.00,42089,24,247182.0,113000.0,1905.0,102408.0,1
624,E09000013,hammersmith and fulham,2011-12-01,36143.0,7.38,42531,30,182445.0,140000.0,1715.0,82390.0,1
625,E09000014,haringey,2011-12-01,28032.0,7.11,30446,26,255540.0,74000.0,2960.0,104173.0,1
626,E09000015,harrow,2011-12-01,27540.0,7.31,32342,48,240499.0,76000.0,5046.0,86524.0,1
627,E09000016,havering,2011-12-01,28415.0,7.35,31947,36,237927.0,82000.0,11446.0,99184.0,1
628,E09000017,hillingdon,2011-12-01,33589.0,7.40,39436,43,275499.0,202000.0,11570.0,103907.0,1
629,E09000018,hounslow,2011-12-01,32759.0,7.26,41142,35,254927.0,150000.0,5659.0,96892.0,1
630,E09000019,islington,2011-12-01,35996.0,7.09,60068,32,206285.0,201000.0,1486.0,96872.0,1
631,E09000020,kensington and chelsea,2011-12-01,31491.0,7.57,38220,34,158251.0,137000.0,1238.0,84798.0,1
632,E09000021,kingston upon thames,2011-12-01,28997.0,7.33,34459,47,160436.0,80000.0,3726.0,65198.0,1
633,E09000022,lambeth,2011-12-01,34836.0,7.13,43657,28,304481.0,150000.0,2725.0,132213.0,1
634,E09000023,lewisham,2011-12-01,29567.0,7.05,30506,17,276938.0,75000.0,3532.0,117651.0,1
635,E09000024,merton,2011-12-01,28066.0,7.14,32415,37,200543.0,86000.0,3762.0,80919.0,1
636,E09000025,newham,2011-12-01,29998.0,7.12,36870,23,310460.0,89000.0,3857.0,103212.0,1
637,E09000026,redbridge,2011-12-01,29829.0,7.33,31948,33,281395.0,77000.0,5644.0,101348.0,1
638,E09000027,richmond upon thames,2011-12-01,32197.0,7.52,37122,45,187527.0,95000.0,5876.0,82482.0,1
639,E09000028,southwark,2011-12-01,36124.0,7.36,48938,27,288717.0,247000.0,2991.0,123265.0,1
640,E09000029,sutton,2011-12-01,26743.0,7.39,29656,37,191123.0,78000.0,4385.0,79696.0,1
641,E09000030,tower hamlets,2011-12-01,45970.0,7.02,86593,27,256012.0,251000.0,2158.0,105379.0,1
642,E09000031,waltham forest,2011-12-01,28005.0,7.18,31926,27,259742.0,71000.0,3881.0,98279.0,1
643,E09000032,wandsworth,2011-12-01,32033.0,7.46,38695,28,307710.0,125000.0,3522.0,134619.0,1
644,E09000033,westminster,2011-12-01,37406.0,7.33,54049,25,219582.0,674000.0,2203.0,118318.0,1
645,E12000001,north east,2011-12-01,23250.0,7.44,27712,38,2596441.0,1130000.0,NaN,NaN,0
646,E12000002,north west,2011-12-01,24167.0,7.37,28634,43,7055961.0,3380000.0,NaN,NaN,0
647,E12000003,yorkshire and the humber,2011-12-01,24119.0,7.39,28172,42,5288212.0,2513000.0,NaN,NaN,0
648,E12000004,east midlands,2011-12-01,24002.0,7.47,28558,47,4537448.0,2198000.0,NaN,NaN,0
649,E12000005,west midlands,2011-12-01,24291.0,7.28,28539,43,5608667.0,2635000.0,NaN,NaN,0
651,E12000007,london,2011-12-01,34396.0,7.25,49831,34,8204407.0,5028000.0,159471.0,3358163.0,0
652,E12000008,south east,2011-12-01,27881.0,7.51,33871,43,8652784.0,4442000.0,NaN,NaN,0
653,E12000009,south west,2011-12-01,24306.0,7.53,28872,47,5300831.0,2718000.0,NaN,NaN,0
656,E92000001,england,2011-12-01,26488.0,7.41,33514,43,53107169.0,26874000.0,13303728.0,22976066.0,0
660,N92000002,northern ireland,2011-12-01,23034.0,7.53,27105,NaN,1814318.0,846000.0,NaN,NaN,0
661,S92000003,scotland,2011-12-01,25291.0,7.51,29985,NaN,5299900.0,2663000.0,NaN,NaN,0
662,W92000004,wales,2011-12-01,23397.0,7.40,26687,NaN,3063758.0,1361000.0,NaN,NaN,0
664,E09000002,barking and dagenham,2012-12-01,33131.0,7.09,37059,27,190560.0,55000.0,3780.0,71431.0,1
665,E09000003,barnet,2012-12-01,29594.0,7.28,33044,33,363956.0,154000.0,8675.0,141461.0,1
666,E09000004,bexley,2012-12-01,27440.0,7.42,30833,54,234271.0,78000.0,6429.0,95240.0,1
667,E09000005,brent,2012-12-01,27577.0,7.28,32089,43,314660.0,123000.0,4323.0,112643.0,1
668,E09000006,bromley,2012-12-01,28082.0,7.60,33859,49,314036.0,122000.0,15013.0,135612.0,1
669,E09000007,camden,2012-12-01,36962.0,7.24,44832,31,224962.0,344000.0,2179.0,100196.0,1
670,E09000008,croydon,2012-12-01,28974.0,7.01,33831,44,368886.0,141000.0,8650.0,148806.0,1
671,E09000009,ealing,2012-12-01,31104.0,7.22,35024,41,340671.0,148000.0,5554.0,127872.0,1
672,E09000010,enfield,2012-12-01,27123.0,7.24,31749,39,317287.0,117000.0,8220.0,122339.0,1
673,E09000011,greenwich,2012-12-01,30097.0,7.15,32764,40,260068.0,82000.0,5044.0,104509.0,1
674,E09000012,hackney,2012-12-01,34803.0,7.07,41030,24,252119.0,112000.0,1905.0,103565.0,1
675,E09000013,hammersmith and fulham,2012-12-01,35136.0,7.21,44065,23,179850.0,147000.0,1715.0,82861.0,1
676,E09000014,haringey,2012-12-01,29116.0,7.17,31874,32,258912.0,80000.0,2960.0,105456.0,1
677,E09000015,harrow,2012-12-01,26738.0,7.37,31817,45,242377.0,79000.0,5046.0,86994.0,1
678,E09000016,havering,2012-12-01,28326.0,7.36,31759,35,239733.0,84000.0,11446.0,99226.0,1
679,E09000017,hillingdon,2012-12-01,33822.0,7.37,39849,43,281756.0,213000.0,11570.0,104896.0,1
680,E09000018,hounslow,2012-12-01,31821.0,7.35,41688,35,259052.0,160000.0,5659.0,97472.0,1
681,E09000019,islington,2012-12-01,36653.0,7.14,58131,31,211047.0,206000.0,1486.0,98096.0,1
682,E09000020,kensington and chelsea,2012-12-01,30726.0,7.70,37192,26,155930.0,144000.0,1238.0,84900.0,1
683,E09000021,kingston upon thames,2012-12-01,29067.0,7.17,36381,46,163906.0,81000.0,3726.0,65422.0,1
684,E09000022,lambeth,2012-12-01,35280.0,7.08,44271,23,310200.0,152000.0,2725.0,133063.0,1
685,E09000023,lewisham,2012-12-01,29995.0,7.23,30823,20,281556.0,78000.0,3532.0,118839.0,1
686,E09000024,merton,2012-12-01,28613.0,7.18,32742,39,202225.0,89000.0,3762.0,81429.0,1
687,E09000025,newham,2012-12-01,30540.0,7.23,35465,21,314084.0,97000.0,3857.0,104121.0,1
688,E09000026,redbridge,2012-12-01,28100.0,7.30,30371,29,284617.0,88000.0,5644.0,101874.0,1
689,E09000027,richmond upon thames,2012-12-01,31505.0,7.40,36411,46,189145.0,92000.0,5876.0,82691.0,1
690,E09000028,southwark,2012-12-01,36056.0,7.21,47611,30,293530.0,270000.0,2991.0,124319.0,1
691,E09000029,sutton,2012-12-01,25247.0,7.28,29407,37,193630.0,79000.0,4385.0,80283.0,1
692,E09000030,tower hamlets,2012-12-01,44880.0,7.32,64782,28,263003.0,253000.0,2158.0,108254.0,1
693,E09000031,waltham forest,2012-12-01,27235.0,7.24,30738,31,262566.0,77000.0,3881.0,98783.0,1
694,E09000032,wandsworth,2012-12-01,31262.0,7.26,35295,24,308312.0,136000.0,3522.0,135601.0,1
695,E09000033,westminster,2012-12-01,37649.0,7.00,55529,22,223858.0,698000.0,2203.0,119245.0,1
696,E12000001,north east,2012-12-01,23781.0,7.39,27977,37,2602310.0,1122000.0,NaN,NaN,0
697,E12000002,north west,2012-12-01,24603.0,7.41,28989,44,7084337.0,3398000.0,NaN,NaN,0
698,E12000003,yorkshire and the humber,2012-12-01,24288.0,7.46,28321,43,5316691.0,2479000.0,NaN,NaN,0
699,E12000004,east midlands,2012-12-01,24626.0,7.50,29039,47,4567731.0,2191000.0,NaN,NaN,0
700,E12000005,west midlands,2012-12-01,24573.0,7.43,28939,44,5642569.0,2659000.0,NaN,NaN,0
702,E12000007,london,2012-12-01,34883.0,7.25,48367,34,8308369.0,5229000.0,159471.0,3383029.0,0
703,E12000008,south east,2012-12-01,28175.0,7.54,34416,43,8724737.0,4477000.0,NaN,NaN,0
704,E12000009,south west,2012-12-01,24581.0,7.55,29058,47,5339637.0,2692000.0,NaN,NaN,0
707,E92000001,england,2012-12-01,26822.0,7.44,33529,43,53493729.0,27117000.0,13303728.0,23110962.0,0
711,N92000002,northern ireland,2012-12-01,23944.0,7.70,27784,NaN,1823634.0,825000.0,NaN,NaN,0
712,S92000003,scotland,2012-12-01,25780.0,7.53,30792,NaN,5313600.0,2643000.0,NaN,NaN,0
713,W92000004,wales,2012-12-01,23617.0,7.44,26950,NaN,3074067.0,1371000.0,NaN,NaN,0
715,E09000002,barking and dagenham,2013-12-01,32248.0,7.01,37214,25,194352.0,54000.0,3780.0,71937.0,1
716,E09000003,barnet,2013-12-01,29353.0,7.40,33766,36,369088.0,159000.0,8675.0,142835.0,1
717,E09000004,bexley,2013-12-01,28512.0,7.28,32463,55,236687.0,80000.0,6429.0,95658.0,1
718,E09000005,brent,2013-12-01,28034.0,7.41,34480,41,317264.0,125000.0,4323.0,113305.0,1
719,E09000006,bromley,2013-12-01,28126.0,7.53,34133,50,317899.0,129000.0,15013.0,136304.0,1
720,E09000007,camden,2013-12-01,36336.0,7.11,45539,29,229719.0,355000.0,2179.0,100760.0,1
721,E09000008,croydon,2013-12-01,30939.0,7.36,35213,42,372752.0,130000.0,8650.0,149697.0,1
722,E09000009,ealing,2013-12-01,29733.0,7.24,33210,40,342494.0,152000.0,5554.0,128862.0,1
723,E09000010,enfield,2013-12-01,25805.0,7.28,30011,39,320524.0,118000.0,8220.0,122888.0,1
724,E09000011,greenwich,2013-12-01,29251.0,7.15,33060,39,264008.0,86000.0,5044.0,104623.0,1
725,E09000012,hackney,2013-12-01,33097.0,7.05,39044,25,257379.0,111000.0,1905.0,104365.0,1
726,E09000013,hammersmith and fulham,2013-12-01,34554.0,7.40,42349,21,178685.0,141000.0,1715.0,83281.0,1
727,E09000014,haringey,2013-12-01,29609.0,7.28,32408,36,263386.0,84000.0,2960.0,106033.0,1
728,E09000015,harrow,2013-12-01,25784.0,7.51,31504,49,243373.0,78000.0,5046.0,87709.0,1
729,E09000016,havering,2013-12-01,29858.0,7.51,32758,32,242080.0,91000.0,11446.0,99463.0,1
730,E09000017,hillingdon,2013-12-01,35738.0,7.50,40911,43,286808.0,213000.0,11570.0,106363.0,1
731,E09000018,hounslow,2013-12-01,31173.0,7.33,38522,35,262407.0,167000.0,5659.0,97704.0,1
732,E09000019,islington,2013-12-01,37325.0,7.35,56967,33,215671.0,220000.0,1486.0,99015.0,1
733,E09000020,kensington and chelsea,2013-12-01,31307.0,7.67,37906,25,155594.0,141000.0,1238.0,84957.0,1
734,E09000021,kingston upon thames,2013-12-01,29450.0,7.43,35167,46,166793.0,80000.0,3726.0,65625.0,1
735,E09000022,lambeth,2013-12-01,35397.0,7.01,43350,21,314242.0,168000.0,2725.0,133598.0,1
736,E09000023,lewisham,2013-12-01,30478.0,7.34,30909,18,286180.0,82000.0,3532.0,120637.0,1
737,E09000024,merton,2013-12-01,28610.0,7.43,31960,39,203223.0,96000.0,3762.0,81842.0,1
738,E09000025,newham,2013-12-01,29334.0,7.24,32807,18,318227.0,104000.0,3857.0,104791.0,1
739,E09000026,redbridge,2013-12-01,31215.0,7.47,33442,29,288272.0,84000.0,5644.0,102138.0,1
740,E09000027,richmond upon thames,2013-12-01,31997.0,7.60,36611,43,191365.0,95000.0,5876.0,83176.0,1
741,E09000028,southwark,2013-12-01,36198.0,7.58,43807,34,298465.0,256000.0,2991.0,125566.0,1
742,E09000029,sutton,2013-12-01,30061.0,7.49,33223,37,195914.0,77000.0,4385.0,80510.0,1
743,E09000030,tower hamlets,2013-12-01,46441.0,7.50,73376,28,272890.0,269000.0,2158.0,109215.0,1
744,E09000031,waltham forest,2013-12-01,NaN,7.34,31143,33,265797.0,81000.0,3881.0,99251.0,1
745,E09000032,wandsworth,2013-12-01,31491.0,7.43,36917,20,310516.0,134000.0,3522.0,136558.0,1
746,E09000033,westminster,2013-12-01,36946.0,7.53,51094,21,226841.0,717000.0,2203.0,119837.0,1
747,E12000001,north east,2013-12-01,24113.0,7.47,28460,38,2610481.0,1132000.0,NaN,NaN,0
748,E12000002,north west,2013-12-01,25111.0,7.42,29569,46,7103261.0,3464000.0,NaN,NaN,0
749,E12000003,yorkshire and the humber,2013-12-01,24933.0,7.51,28997,44,5337711.0,2523000.0,NaN,NaN,0
750,E12000004,east midlands,2013-12-01,24918.0,7.55,29415,46,4598431.0,2186000.0,NaN,NaN,0
751,E12000005,west midlands,2013-12-01,25328.0,7.49,30162,42,5674712.0,2700000.0,NaN,NaN,0
753,E12000007,london,2013-12-01,35173.0,7.36,47962,34,8416543.0,5341000.0,159471.0,3404068.0,0
754,E12000008,south east,2013-12-01,28315.0,7.60,34214,44,8792766.0,4565000.0,NaN,NaN,0
755,E12000009,south west,2013-12-01,25242.0,7.56,30016,47,5377596.0,2745000.0,NaN,NaN,0
758,E92000001,england,2013-12-01,27372.0,7.50,33967,43,53865817.0,27545000.0,13303728.0,23235684.0,0
762,N92000002,northern ireland,2013-12-01,23952.0,7.73,27839,NaN,1829725.0,834000.0,NaN,NaN,0
763,S92000003,scotland,2013-12-01,26489.0,7.58,31486,NaN,5327700.0,2634000.0,NaN,NaN,0
764,W92000004,wales,2013-12-01,24103.0,7.52,27518,NaN,3082412.0,1395000.0,NaN,NaN,0
766,E09000002,barking and dagenham,2014-12-01,32698.0,7.32,36323,23,198294.0,59000.0,3780.0,72668.0,1
767,E09000003,barnet,2014-12-01,31162.0,7.54,34936,38,374915.0,165000.0,8675.0,143948.0,1
768,E09000004,bexley,2014-12-01,28505.0,7.52,31878,54,239865.0,80000.0,6429.0,96186.0,1
769,E09000005,brent,2014-12-01,29514.0,7.24,33484,35,320762.0,131000.0,4323.0,114039.0,1
770,E09000006,bromley,2014-12-01,27926.0,7.71,33458,48,321278.0,127000.0,15013.0,136453.0,1
771,E09000007,camden,2014-12-01,36748.0,7.25,44629,26,234846.0,379000.0,2179.0,101214.0,1
772,E09000008,croydon,2014-12-01,31154.0,7.35,34769,40,376040.0,142000.0,8650.0,150992.0,1
773,E09000009,ealing,2014-12-01,28825.0,7.60,32716,40,342118.0,159000.0,5554.0,129631.0,1
774,E09000010,enfield,2014-12-01,25805.0,7.45,29804,39,324574.0,127000.0,8220.0,123400.0,1
775,E09000011,greenwich,2014-12-01,28954.0,7.33,31690,34,268678.0,95000.0,5044.0,105735.0,1
776,E09000012,hackney,2014-12-01,33116.0,7.43,40241,25,263150.0,131000.0,1905.0,105490.0,1
777,E09000013,hammersmith and fulham,2014-12-01,33688.0,7.56,38677,21,178365.0,148000.0,1715.0,83907.0,1
778,E09000014,haringey,2014-12-01,30325.0,7.38,33616,37,267541.0,90000.0,2960.0,106507.0,1
779,E09000015,harrow,2014-12-01,26037.0,7.49,29957,45,246011.0,89000.0,5046.0,88004.0,1
780,E09000016,havering,2014-12-01,30003.0,7.62,33536,32,245974.0,90000.0,11446.0,99619.0,1
781,E09000017,hillingdon,2014-12-01,33984.0,7.63,42606,44,292690.0,220000.0,11570.0,106917.0,1
782,E09000018,hounslow,2014-12-01,33038.0,7.57,41473,35,265568.0,164000.0,5659.0,98390.0,1
783,E09000019,islington,2014-12-01,36751.0,7.36,59007,33,221030.0,231000.0,1486.0,100258.0,1
784,E09000020,kensington and chelsea,2014-12-01,30002.0,7.65,36844,25,156190.0,141000.0,1238.0,85553.0,1
785,E09000021,kingston upon thames,2014-12-01,30768.0,7.52,35833,46,169958.0,82000.0,3726.0,65886.0,1
786,E09000022,lambeth,2014-12-01,34491.0,7.41,44566,28,318216.0,180000.0,2725.0,134852.0,1
787,E09000023,lewisham,2014-12-01,29983.0,7.33,32256,17,291933.0,88000.0,3532.0,121350.0,1
788,E09000024,merton,2014-12-01,27539.0,7.64,31917,38,203515.0,97000.0,3762.0,82282.0,1
789,E09000025,newham,2014-12-01,29061.0,7.54,33619,17,324322.0,112000.0,3857.0,106760.0,1
790,E09000026,redbridge,2014-12-01,31127.0,7.55,33732,29,293055.0,89000.0,5644.0,102396.0,1
791,E09000027,richmond upon thames,2014-12-01,31533.0,7.54,36975,41,193585.0,95000.0,5876.0,83540.0,1
792,E09000028,southwark,2014-12-01,34612.0,7.43,40893,35,302538.0,282000.0,2991.0,127217.0,1
793,E09000029,sutton,2014-12-01,25797.0,7.60,30752,38,198134.0,78000.0,4385.0,80810.0,1
794,E09000030,tower hamlets,2014-12-01,48309.0,7.54,74087,28,284015.0,278000.0,2158.0,109875.0,1
795,E09000031,waltham forest,2014-12-01,26484.0,7.64,28426,36,268020.0,84000.0,3881.0,99640.0,1
796,E09000032,wandsworth,2014-12-01,31085.0,7.47,35182,21,312145.0,134000.0,3522.0,137757.0,1
797,E09000033,westminster,2014-12-01,37260.0,7.45,51099,19,233292.0,737000.0,2203.0,120367.0,1
798,E12000001,north east,2014-12-01,24904.0,7.57,28957,38,2618710.0,1162000.0,NaN,NaN,0
799,E12000002,north west,2014-12-01,25262.0,7.56,29901,47,7132991.0,3523000.0,NaN,NaN,0
800,E12000003,yorkshire and the humber,2014-12-01,24999.0,7.55,28957,44,5360027.0,2585000.0,NaN,NaN,0
801,E12000004,east midlands,2014-12-01,25000.0,7.64,29346,45,4637413.0,2232000.0,NaN,NaN,0
802,E12000005,west midlands,2014-12-01,24963.0,7.57,29550,42,5713284.0,2742000.0,NaN,NaN,0
804,E12000007,london,2014-12-01,35034.0,7.49,48263,33,8538689.0,5603000.0,159471.0,3427645.0,0
805,E12000008,south east,2014-12-01,28607.0,7.73,34646,45,8873818.0,4651000.0,NaN,NaN,0
806,E12000009,south west,2014-12-01,25585.0,7.66,30163,48,5423303.0,2849000.0,NaN,NaN,0
809,E92000001,england,2014-12-01,27485.0,7.60,34214,44,54316618.0,28327000.0,13303728.0,23372289.0,0
813,N92000002,northern ireland,2014-12-01,24491.0,7.89,28263,NaN,1840498.0,848000.0,NaN,NaN,0
814,S92000003,scotland,2014-12-01,27038.0,7.66,31484,NaN,5347600.0,2733000.0,NaN,NaN,0
815,W92000004,wales,2014-12-01,24453.0,7.56,27759,NaN,3092036.0,1396000.0,NaN,NaN,0
817,E09000002,barking and dagenham,2015-12-01,33018.0,7.45,36705,19,201979.0,62000.0,3780.0,73182.0,1
818,E09000003,barnet,2015-12-01,30900.0,7.53,34730,37,379691.0,168000.0,8675.0,145272.0,1
819,E09000004,bexley,2015-12-01,29664.0,7.41,33367,52,242142.0,86000.0,6429.0,96996.0,1
820,E09000005,brent,2015-12-01,29987.0,7.55,34281,36,324012.0,136000.0,4323.0,115598.0,1
821,E09000006,bromley,2015-12-01,30444.0,7.54,35238,46,324857.0,124000.0,15013.0,136864.0,1
822,E09000007,camden,2015-12-01,36970.0,7.35,45489,25,241059.0,383000.0,2179.0,101653.0,1
823,E09000008,croydon,2015-12-01,30628.0,7.45,34199,38,379031.0,144000.0,8650.0,152515.0,1
824,E09000009,ealing,2015-12-01,28657.0,7.65,31980,43,343059.0,163000.0,5554.0,130528.0,1
825,E09000010,enfield,2015-12-01,26230.0,7.30,31041,36,328433.0,133000.0,8220.0,123799.0,1
826,E09000011,greenwich,2015-12-01,30497.0,7.23,33856,35,274803.0,96000.0,5044.0,106883.0,1
827,E09000012,hackney,2015-12-01,31566.0,7.31,38327,25,269009.0,136000.0,1905.0,106748.0,1
828,E09000013,hammersmith and fulham,2015-12-01,34652.0,7.68,38176,22,179410.0,154000.0,1715.0,85267.0,1
829,E09000014,haringey,2015-12-01,30072.0,7.26,33919,36,272864.0,93000.0,2960.0,106640.0,1
830,E09000015,harrow,2015-12-01,26770.0,7.65,31404,41,247130.0,88000.0,5046.0,88414.0,1
831,E09000016,havering,2015-12-01,30591.0,7.69,33850,32,249085.0,93000.0,11446.0,100261.0,1
832,E09000017,hillingdon,2015-12-01,32681.0,7.46,40529,44,297735.0,202000.0,11570.0,107462.0,1
833,E09000018,hounslow,2015-12-01,33717.0,7.54,43037,34,268770.0,187000.0,5659.0,98787.0,1
834,E09000019,islington,2015-12-01,36679.0,7.29,49576,29,227692.0,250000.0,1486.0,100756.0,1
835,E09000020,kensington and chelsea,2015-12-01,31524.0,7.78,38848,26,157711.0,150000.0,1238.0,86537.0,1
836,E09000021,kingston upon thames,2015-12-01,28635.0,7.71,31728,46,173525.0,95000.0,3726.0,66412.0,1
837,E09000022,lambeth,2015-12-01,34852.0,7.41,45180,29,324431.0,185000.0,2725.0,136263.0,1
838,E09000023,lewisham,2015-12-01,30932.0,7.14,32602,18,297325.0,83000.0,3532.0,122818.0,1
839,E09000024,merton,2015-12-01,30040.0,7.56,32907,35,204565.0,98000.0,3762.0,82707.0,1
840,E09000025,newham,2015-12-01,28886.0,7.73,33127,15,332817.0,114000.0,3857.0,108810.0,1
841,E09000026,redbridge,2015-12-01,29098.0,7.87,33182,28,296793.0,92000.0,5644.0,102653.0,1
842,E09000027,richmond upon thames,2015-12-01,32660.0,7.74,38060,41,194730.0,102000.0,5876.0,83781.0,1
843,E09000028,southwark,2015-12-01,36238.0,7.49,42316,35,308901.0,289000.0,2991.0,128358.0,1
844,E09000029,sutton,2015-12-01,27355.0,7.45,32427,35,200145.0,80000.0,4385.0,81237.0,1
845,E09000030,tower hamlets,2015-12-01,46681.0,7.48,67320,27,295236.0,298000.0,2158.0,110791.0,1
846,E09000031,waltham forest,2015-12-01,29352.0,7.55,30911,35,271170.0,86000.0,3881.0,100311.0,1
847,E09000032,wandsworth,2015-12-01,31968.0,7.53,37251,21,314544.0,144000.0,3522.0,138841.0,1
848,E09000033,westminster,2015-12-01,39392.0,7.60,53316,17,242299.0,756000.0,2203.0,121116.0,1
849,E12000001,north east,2015-12-01,25347.0,7.62,29989,38,2624621.0,1196000.0,NaN,NaN,0
850,E12000002,north west,2015-12-01,25667.0,7.55,30351,47,7173835.0,3603000.0,NaN,NaN,0
851,E12000003,yorkshire and the humber,2015-12-01,25194.0,7.65,29371,44,5390576.0,2694000.0,NaN,NaN,0
852,E12000004,east midlands,2015-12-01,25003.0,7.74,29407,45,4677038.0,2304000.0,NaN,NaN,0
853,E12000005,west midlands,2015-12-01,25682.0,7.62,30179,42,5751000.0,2818000.0,NaN,NaN,0
855,E12000007,london,2015-12-01,35303.0,7.50,46946,33,8673713.0,5810000.0,159471.0,3454488.0,0

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
613,E09000002,barking and dagenham,2011-12-01,28201.0,7.05,33568,30,187029.0,54000.0,3780.0,71079.0,1
614,E09000003,barnet,2011-12-01,30237.0,7.43,33062,34,357538.0,147000.0,8675.0,139346.0,1
615,E09000004,bexley,2011-12-01,28638.0,7.42,31812,54,232774.0,78000.0,6429.0,95037.0,1
616,E09000005,brent,2011-12-01,26772.0,7.11,29609,37,312245.0,115000.0,4323.0,112083.0,1
617,E09000006,bromley,2011-12-01,28163.0,7.50,32863,50,310554.0,119000.0,15013.0,135036.0,1
618,E09000007,camden,2011-12-01,35967.0,7.25,45588,33,220087.0,331000.0,2179.0,99828.0,1
619,E09000008,croydon,2011-12-01,28979.0,7.04,33050,38,364815.0,136000.0,8650.0,148099.0,1
620,E09000009,ealing,2011-12-01,28646.0,7.22,34725,41,339314.0,148000.0,5554.0,127187.0,1
621,E09000010,enfield,2011-12-01,26412.0,7.23,31797,35,313935.0,110000.0,8220.0,122042.0,1
622,E09000011,greenwich,2011-12-01,29932.0,7.18,32581,39,255483.0,81000.0,5044.0,103186.0,1
623,E09000012,hackney,2011-12-01,33512.0,7.00,42089,24,247182.0,113000.0,1905.0,102408.0,1
624,E09000013,hammersmith and fulham,2011-12-01,36143.0,7.38,42531,30,182445.0,140000.0,1715.0,82390.0,1
625,E09000014,haringey,2011-12-01,28032.0,7.11,30446,26,255540.0,74000.0,2960.0,104173.0,1
626,E09000015,harrow,2011-12-01,27540.0,7.31,32342,48,240499.0,76000.0,5046.0,86524.0,1
627,E09000016,havering,2011-12-01,28415.0,7.35,31947,36,237927.0,82000.0,11446.0,99184.0,1
628,E09000017,hillingdon,2011-12-01,33589.0,7.40,39436,43,275499.0,202000.0,11570.0,103907.0,1
629,E09000018,hounslow,2011-12-01,32759.0,7.26,41142,35,254927.0,150000.0,5659.0,96892.0,1
630,E09000019,islington,2011-12-01,35996.0,7.09,60068,32,206285.0,201000.0,1486.0,96872.0,1
631,E09000020,kensington and chelsea,2011-12-01,31491.0,7.57,38220,34,158251.0,137000.0,1238.0,84798.0,1
632,E09000021,kingston upon thames,2011-12-01,28997.0,7.33,34459,47,160436.0,80000.0,3726.0,65198.0,1
633,E09000022,lambeth,2011-12-01,34836.0,7.13,43657,28,304481.0,150000.0,2725.0,132213.0,1
634,E09000023,lewisham,2011-12-01,29567.0,7.05,30506,17,276938.0,75000.0,3532.0,117651.0,1
635,E09000024,merton,2011-12-01,28066.0,7.14,32415,37,200543.0,86000.0,3762.0,80919.0,1
636,E09000025,newham,2011-12-01,29998.0,7.12,36870,23,310460.0,89000.0,3857.0,103212.0,1
637,E09000026,redbridge,2011-12-01,29829.0,7.33,31948,33,281395.0,77000.0,5644.0,101348.0,1
638,E09000027,richmond upon thames,2011-12-01,32197.0,7.52,37122,45,187527.0,95000.0,5876.0,82482.0,1
639,E09000028,southwark,2011-12-01,36124.0,7.36,48938,27,288717.0,247000.0,2991.0,123265.0,1
640,E09000029,sutton,2011-12-01,26743.0,7.39,29656,37,191123.0,78000.0,4385.0,79696.0,1
641,E09000030,tower hamlets,2011-12-01,45970.0,7.02,86593,27,256012.0,251000.0,2158.0,105379.0,1
642,E09000031,waltham forest,2011-12-01,28005.0,7.18,31926,27,259742.0,71000.0,3881.0,98279.0,1
643,E09000032,wandsworth,2011-12-01,32033.0,7.46,38695,28,307710.0,125000.0,3522.0,134619.0,1
644,E09000033,westminster,2011-12-01,37406.0,7.33,54049,25,219582.0,674000.0,2203.0,118318.0,1
651,E12000007,london,2011-12-01,34396.0,7.25,49831,34,8204407.0,5028000.0,159471.0,3358163.0,0
656,E92000001,england,2011-12-01,26488.0,7.41,33514,43,53107169.0,26874000.0,13303728.0,22976066.0,0
664,E09000002,barking and dagenham,2012-12-01,33131.0,7.09,37059,27,190560.0,55000.0,3780.0,71431.0,1
665,E09000003,barnet,2012-12-01,29594.0,7.28,33044,33,363956.0,154000.0,8675.0,141461.0,1
666,E09000004,bexley,2012-12-01,27440.0,7.42,30833,54,234271.0,78000.0,6429.0,95240.0,1
667,E09000005,brent,2012-12-01,27577.0,7.28,32089,43,314660.0,123000.0,4323.0,112643.0,1
668,E09000006,bromley,2012-12-01,28082.0,7.60,33859,49,314036.0,122000.0,15013.0,135612.0,1
669,E09000007,camden,2012-12-01,36962.0,7.24,44832,31,224962.0,344000.0,2179.0,100196.0,1
670,E09000008,croydon,2012-12-01,28974.0,7.01,33831,44,368886.0,141000.0,8650.0,148806.0,1
671,E09000009,ealing,2012-12-01,31104.0,7.22,35024,41,340671.0,148000.0,5554.0,127872.0,1
672,E09000010,enfield,2012-12-01,27123.0,7.24,31749,39,317287.0,117000.0,8220.0,122339.0,1
673,E09000011,greenwich,2012-12-01,30097.0,7.15,32764,40,260068.0,82000.0,5044.0,104509.0,1
674,E09000012,hackney,2012-12-01,34803.0,7.07,41030,24,252119.0,112000.0,1905.0,103565.0,1
675,E09000013,hammersmith and fulham,2012-12-01,35136.0,7.21,44065,23,179850.0,147000.0,1715.0,82861.0,1
676,E09000014,haringey,2012-12-01,29116.0,7.17,31874,32,258912.0,80000.0,2960.0,105456.0,1
677,E09000015,harrow,2012-12-01,26738.0,7.37,31817,45,242377.0,79000.0,5046.0,86994.0,1
678,E09000016,havering,2012-12-01,28326.0,7.36,31759,35,239733.0,84000.0,11446.0,99226.0,1
679,E09000017,hillingdon,2012-12-01,33822.0,7.37,39849,43,281756.0,213000.0,11570.0,104896.0,1
680,E09000018,hounslow,2012-12-01,31821.0,7.35,41688,35,259052.0,160000.0,5659.0,97472.0,1
681,E09000019,islington,2012-12-01,36653.0,7.14,58131,31,211047.0,206000.0,1486.0,98096.0,1
682,E09000020,kensington and chelsea,2012-12-01,30726.0,7.70,37192,26,155930.0,144000.0,1238.0,84900.0,1
683,E09000021,kingston upon thames,2012-12-01,29067.0,7.17,36381,46,163906.0,81000.0,3726.0,65422.0,1
684,E09000022,lambeth,2012-12-01,35280.0,7.08,44271,23,310200.0,152000.0,2725.0,133063.0,1
685,E09000023,lewisham,2012-12-01,29995.0,7.23,30823,20,281556.0,78000.0,3532.0,118839.0,1
686,E09000024,merton,2012-12-01,28613.0,7.18,32742,39,202225.0,89000.0,3762.0,81429.0,1
687,E09000025,newham,2012-12-01,30540.0,7.23,35465,21,314084.0,97000.0,3857.0,104121.0,1
688,E09000026,redbridge,2012-12-01,28100.0,7.30,30371,29,284617.0,88000.0,5644.0,101874.0,1
689,E09000027,richmond upon thames,2012-12-01,31505.0,7.40,36411,46,189145.0,92000.0,5876.0,82691.0,1
690,E09000028,southwark,2012-12-01,36056.0,7.21,47611,30,293530.0,270000.0,2991.0,124319.0,1
691,E09000029,sutton,2012-12-01,25247.0,7.28,29407,37,193630.0,79000.0,4385.0,80283.0,1
692,E09000030,tower hamlets,2012-12-01,44880.0,7.32,64782,28,263003.0,253000.0,2158.0,108254.0,1
693,E09000031,waltham forest,2012-12-01,27235.0,7.24,30738,31,262566.0,77000.0,3881.0,98783.0,1
694,E09000032,wandsworth,2012-12-01,31262.0,7.26,35295,24,308312.0,136000.0,3522.0,135601.0,1
695,E09000033,westminster,2012-12-01,37649.0,7.00,55529,22,223858.0,698000.0,2203.0,119245.0,1
702,E12000007,london,2012-12-01,34883.0,7.25,48367,34,8308369.0,5229000.0,159471.0,3383029.0,0
707,E92000001,england,2012-12-01,26822.0,7.44,33529,43,53493729.0,27117000.0,13303728.0,23110962.0,0
715,E09000002,barking and dagenham,2013-12-01,32248.0,7.01,37214,25,194352.0,54000.0,3780.0,71937.0,1
716,E09000003,barnet,2013-12-01,29353.0,7.40,33766,36,369088.0,159000.0,8675.0,142835.0,1
717,E09000004,bexley,2013-12-01,28512.0,7.28,32463,55,236687.0,80000.0,6429.0,95658.0,1
718,E09000005,brent,2013-12-01,28034.0,7.41,34480,41,317264.0,125000.0,4323.0,113305.0,1
719,E09000006,bromley,2013-12-01,28126.0,7.53,34133,50,317899.0,129000.0,15013.0,136304.0,1
720,E09000007,camden,2013-12-01,36336.0,7.11,45539,29,229719.0,355000.0,2179.0,100760.0,1
721,E09000008,croydon,2013-12-01,30939.0,7.36,35213,42,372752.0,130000.0,8650.0,149697.0,1
722,E09000009,ealing,2013-12-01,29733.0,7.24,33210,40,342494.0,152000.0,5554.0,128862.0,1
723,E09000010,enfield,2013-12-01,25805.0,7.28,30011,39,320524.0,118000.0,8220.0,122888.0,1
724,E09000011,greenwich,2013-12-01,29251.0,7.15,33060,39,264008.0,86000.0,5044.0,104623.0,1
725,E09000012,hackney,2013-12-01,33097.0,7.05,39044,25,257379.0,111000.0,1905.0,104365.0,1
726,E09000013,hammersmith and fulham,2013-12-01,34554.0,7.40,42349,21,178685.0,141000.0,1715.0,83281.0,1
727,E09000014,haringey,2013-12-01,29609.0,7.28,32408,36,263386.0,84000.0,2960.0,106033.0,1
728,E09000015,harrow,2013-12-01,25784.0,7.51,31504,49,243373.0,78000.0,5046.0,87709.0,1
729,E09000016,havering,2013-12-01,29858.0,7.51,32758,32,242080.0,91000.0,11446.0,99463.0,1
730,E09000017,hillingdon,2013-12-01,35738.0,7.50,40911,43,286808.0,213000.0,11570.0,106363.0,1
731,E09000018,hounslow,2013-12-01,31173.0,7.33,38522,35,262407.0,167000.0,5659.0,97704.0,1
732,E09000019,islington,2013-12-01,37325.0,7.35,56967,33,215671.0,220000.0,1486.0,99015.0,1
733,E09000020,kensington and chelsea,2013-12-01,31307.0,7.67,37906,25,155594.0,141000.0,1238.0,84957.0,1
734,E09000021,kingston upon thames,2013-12-01,29450.0,7.43,35167,46,166793.0,80000.0,3726.0,65625.0,1
735,E09000022,lambeth,2013-12-01,35397.0,7.01,43350,21,314242.0,168000.0,2725.0,133598.0,1
736,E09000023,lewisham,2013-12-01,30478.0,7.34,30909,18,286180.0,82000.0,3532.0,120637.0,1
737,E09000024,merton,2013-12-01,28610.0,7.43,31960,39,203223.0,96000.0,3762.0,81842.0,1
738,E09000025,newham,2013-12-01,29334.0,7.24,32807,18,318227.0,104000.0,3857.0,104791.0,1
739,E09000026,redbridge,2013-12-01,31215.0,7.47,33442,29,288272.0,84000.0,5644.0,102138.0,1
740,E09000027,richmond upon thames,2013-12-01,31997.0,7.60,36611,43,191365.0,95000.0,5876.0,83176.0,1
741,E09000028,southwark,2013-12-01,36198.0,7.58,43807,34,298465.0,256000.0,2991.0,125566.0,1
742,E09000029,sutton,2013-12-01,30061.0,7.49,33223,37,195914.0,77000.0,4385.0,80510.0,1
743,E09000030,tower hamlets,2013-12-01,46441.0,7.50,73376,28,272890.0,269000.0,2158.0,109215.0,1
745,E09000032,wandsworth,2013-12-01,31491.0,7.43,36917,20,310516.0,134000.0,3522.0,136558.0,1
746,E09000033,westminster,2013-12-01,36946.0,7.53,51094,21,226841.0,717000.0,2203.0,119837.0,1
753,E12000007,london,2013-12-01,35173.0,7.36,47962,34,8416543.0,5341000.0,159471.0,3404068.0,0
758,E92000001,england,2013-12-01,27372.0,7.50,33967,43,53865817.0,27545000.0,13303728.0,23235684.0,0
766,E09000002,barking and dagenham,2014-12-01,32698.0,7.32,36323,23,198294.0,59000.0,3780.0,72668.0,1
767,E09000003,barnet,2014-12-01,31162.0,7.54,34936,38,374915.0,165000.0,8675.0,143948.0,1
768,E09000004,bexley,2014-12-01,28505.0,7.52,31878,54,239865.0,80000.0,6429.0,96186.0,1
769,E09000005,brent,2014-12-01,29514.0,7.24,33484,35,320762.0,131000.0,4323.0,114039.0,1
770,E09000006,bromley,2014-12-01,27926.0,7.71,33458,48,321278.0,127000.0,15013.0,136453.0,1
771,E09000007,camden,2014-12-01,36748.0,7.25,44629,26,234846.0,379000.0,2179.0,101214.0,1
772,E09000008,croydon,2014-12-01,31154.0,7.35,34769,40,376040.0,142000.0,8650.0,150992.0,1
773,E09000009,ealing,2014-12-01,28825.0,7.60,32716,40,342118.0,159000.0,5554.0,129631.0,1
774,E09000010,enfield,2014-12-01,25805.0,7.45,29804,39,324574.0,127000.0,8220.0,123400.0,1
775,E09000011,greenwich,2014-12-01,28954.0,7.33,31690,34,268678.0,95000.0,5044.0,105735.0,1
776,E09000012,hackney,2014-12-01,33116.0,7.43,40241,25,263150.0,131000.0,1905.0,105490.0,1
777,E09000013,hammersmith and fulham,2014-12-01,33688.0,7.56,38677,21,178365.0,148000.0,1715.0,83907.0,1
778,E09000014,haringey,2014-12-01,30325.0,7.38,33616,37,267541.0,90000.0,2960.0,106507.0,1
779,E09000015,harrow,2014-12-01,26037.0,7.49,29957,45,246011.0,89000.0,5046.0,88004.0,1
780,E09000016,havering,2014-12-01,30003.0,7.62,33536,32,245974.0,90000.0,11446.0,99619.0,1
781,E09000017,hillingdon,2014-12-01,33984.0,7.63,42606,44,292690.0,220000.0,11570.0,106917.0,1
782,E09000018,hounslow,2014-12-01,33038.0,7.57,41473,35,265568.0,164000.0,5659.0,98390.0,1
783,E09000019,islington,2014-12-01,36751.0,7.36,59007,33,221030.0,231000.0,1486.0,100258.0,1
784,E09000020,kensington and chelsea,2014-12-01,30002.0,7.65,36844,25,156190.0,141000.0,1238.0,85553.0,1
785,E09000021,kingston upon thames,2014-12-01,30768.0,7.52,35833,46,169958.0,82000.0,3726.0,65886.0,1
786,E09000022,lambeth,2014-12-01,34491.0,7.41,44566,28,318216.0,180000.0,2725.0,134852.0,1
787,E09000023,lewisham,2014-12-01,29983.0,7.33,32256,17,291933.0,88000.0,3532.0,121350.0,1
788,E09000024,merton,2014-12-01,27539.0,7.64,31917,38,203515.0,97000.0,3762.0,82282.0,1
789,E09000025,newham,2014-12-01,29061.0,7.54,33619,17,324322.0,112000.0,3857.0,106760.0,1
790,E09000026,redbridge,2014-12-01,31127.0,7.55,33732,29,293055.0,89000.0,5644.0,102396.0,1
791,E09000027,richmond upon thames,2014-12-01,31533.0,7.54,36975,41,193585.0,95000.0,5876.0,83540.0,1
792,E09000028,southwark,2014-12-01,34612.0,7.43,40893,35,302538.0,282000.0,2991.0,127217.0,1
793,E09000029,sutton,2014-12-01,25797.0,7.60,30752,38,198134.0,78000.0,4385.0,80810.0,1
794,E09000030,tower hamlets,2014-12-01,48309.0,7.54,74087,28,284015.0,278000.0,2158.0,109875.0,1
795,E09000031,waltham forest,2014-12-01,26484.0,7.64,28426,36,268020.0,84000.0,3881.0,99640.0,1
796,E09000032,wandsworth,2014-12-01,31085.0,7.47,35182,21,312145.0,134000.0,3522.0,137757.0,1
797,E09000033,westminster,2014-12-01,37260.0,7.45,51099,19,233292.0,737000.0,2203.0,120367.0,1
804,E12000007,london,2014-12-01,35034.0,7.49,48263,33,8538689.0,5603000.0,159471.0,3427645.0,0
809,E92000001,england,2014-12-01,27485.0,7.60,34214,44,54316618.0,28327000.0,13303728.0,23372289.0,0
817,E09000002,barking and dagenham,2015-12-01,33018.0,7.45,36705,19,201979.0,62000.0,3780.0,73182.0,1
818,E09000003,barnet,2015-12-01,30900.0,7.53,34730,37,379691.0,168000.0,8675.0,145272.0,1
819,E09000004,bexley,2015-12-01,29664.0,7.41,33367,52,242142.0,86000.0,6429.0,96996.0,1
820,E09000005,brent,2015-12-01,29987.0,7.55,34281,36,324012.0,136000.0,4323.0,115598.0,1
821,E09000006,bromley,2015-12-01,30444.0,7.54,35238,46,324857.0,124000.0,15013.0,136864.0,1
822,E09000007,camden,2015-12-01,36970.0,7.35,45489,25,241059.0,383000.0,2179.0,101653.0,1
823,E09000008,croydon,2015-12-01,30628.0,7.45,34199,38,379031.0,144000.0,8650.0,152515.0,1
824,E09000009,ealing,2015-12-01,28657.0,7.65,31980,43,343059.0,163000.0,5554.0,130528.0,1
825,E09000010,enfield,2015-12-01,26230.0,7.30,31041,36,328433.0,133000.0,8220.0,123799.0,1
826,E09000011,greenwich,2015-12-01,30497.0,7.23,33856,35,274803.0,96000.0,5044.0,106883.0,1
827,E09000012,hackney,2015-12-01,31566.0,7.31,38327,25,269009.0,136000.0,1905.0,106748.0,1
828,E09000013,hammersmith and fulham,2015-12-01,34652.0,7.68,38176,22,179410.0,154000.0,1715.0,85267.0,1
829,E09000014,haringey,2015-12-01,30072.0,7.26,33919,36,272864.0,93000.0,2960.0,106640.0,1
830,E09000015,harrow,2015-12-01,26770.0,7.65,31404,41,247130.0,88000.0,5046.0,88414.0,1
831,E09000016,havering,2015-12-01,30591.0,7.69,33850,32,249085.0,93000.0,11446.0,100261.0,1
832,E09000017,hillingdon,2015-12-01,32681.0,7.46,40529,44,297735.0,202000.0,11570.0,107462.0,1
833,E09000018,hounslow,2015-12-01,33717.0,7.54,43037,34,268770.0,187000.0,5659.0,98787.0,1
834,E09000019,islington,2015-12-01,36679.0,7.29,49576,29,227692.0,250000.0,1486.0,100756.0,1
835,E09000020,kensington and chelsea,2015-12-01,31524.0,7.78,38848,26,157711.0,150000.0,1238.0,86537.0,1
836,E09000021,kingston upon thames,2015-12-01,28635.0,7.71,31728,46,173525.0,95000.0,3726.0,66412.0,1
837,E09000022,lambeth,2015-12-01,34852.0,7.41,45180,29,324431.0,185000.0,2725.0,136263.0,1
838,E09000023,lewisham,2015-12-01,30932.0,7.14,32602,18,297325.0,83000.0,3532.0,122818.0,1
839,E09000024,merton,2015-12-01,30040.0,7.56,32907,35,204565.0,98000.0,3762.0,82707.0,1
840,E09000025,newham,2015-12-01,28886.0,7.73,33127,15,332817.0,114000.0,3857.0,108810.0,1
841,E09000026,redbridge,2015-12-01,29098.0,7.87,33182,28,296793.0,92000.0,5644.0,102653.0,1
842,E09000027,richmond upon thames,2015-12-01,32660.0,7.74,38060,41,194730.0,102000.0,5876.0,83781.0,1
843,E09000028,southwark,2015-12-01,36238.0,7.49,42316,35,308901.0,289000.0,2991.0,128358.0,1
844,E09000029,sutton,2015-12-01,27355.0,7.45,32427,35,200145.0,80000.0,4385.0,81237.0,1
845,E09000030,tower hamlets,2015-12-01,46681.0,7.48,67320,27,295236.0,298000.0,2158.0,110791.0,1
846,E09000031,waltham forest,2015-12-01,29352.0,7.55,30911,35,271170.0,86000.0,3881.0,100311.0,1
847,E09000032,wandsworth,2015-12-01,31968.0,7.53,37251,21,314544.0,144000.0,3522.0,138841.0,1
848,E09000033,westminster,2015-12-01,39392.0,7.60,53316,17,242299.0,756000.0,2203.0,121116.0,1
855,E12000007,london,2015-12-01,35303.0,7.50,46946,33,8673713.0,5810000.0,159471.0,3454488.0,0
860,E92000001,england,2015-12-01,27841.0,7.64,34231,43,54786327.0,29219000.0,13303728.0,23542982.0,0
868,E09000002,barking and dagenham,2016-12-01,30994.0,7.50,37959,25,206460.0,63000.0,3780.0,73914.0,1
869,E09000003,barnet,2016-12-01,32623.0,7.47,35315,37,386083.0,169000.0,8675.0,146730.0,1
871,E09000005,brent,2016-12-01,30699.0,7.67,36579,36,328254.0,148000.0,4323.0,116649.0,1
872,E09000006,bromley,2016-12-01,30861.0,7.60,35338,47,326889.0,134000.0,15013.0,137564.0,1
873,E09000007,camden,2016-12-01,37817.0,7.56,45644,27,246181.0,394000.0,2179.0,102618.0,1
874,E09000008,croydon,2016-12-01,31479.0,7.68,#,39,382304.0,149000.0,8650.0,154559.0,1
875,E09000009,ealing,2016-12-01,29241.0,7.42,34468,51,343196.0,168000.0,5554.0,131249.0,1
876,E09000010,enfield,2016-12-01,28918.0,7.29,33076,37,331395.0,129000.0,8220.0,124471.0,1
877,E09000011,greenwich,2016-12-01,30180.0,7.28,33568,35,279766.0,96000.0,5044.0,108603.0,1
878,E09000012,hackney,2016-12-01,32404.0,7.26,39387,27,273526.0,143000.0,1905.0,107574.0,1
879,E09000013,hammersmith and fulham,2016-12-01,35000.0,7.47,40291,23,179654.0,157000.0,1715.0,85635.0,1
880,E09000014,haringey,2016-12-01,29753.0,7.56,32799,36,278451.0,92000.0,2960.0,106879.0,1
881,E09000015,harrow,2016-12-01,30134.0,7.64,34743,40,248752.0,93000.0,5046.0,89324.0,1
882,E09000016,havering,2016-12-01,28906.0,7.53,33025,37,252783.0,100000.0,11446.0,101273.0,1
883,E09000017,hillingdon,2016-12-01,33093.0,7.68,39729,43,302471.0,204000.0,11570.0,108171.0,1
884,E09000018,hounslow,2016-12-01,36235.0,7.96,47577,30,271139.0,197000.0,5659.0,99267.0,1
885,E09000019,islington,2016-12-01,39894.0,7.38,52885,32,232865.0,251000.0,1486.0,101783.0,1
886,E09000020,kensington and chelsea,2016-12-01,30008.0,7.52,35249,26,156726.0,153000.0,1238.0,86921.0,1
887,E09000021,kingston upon thames,2016-12-01,30729.0,7.69,34343,47,176107.0,99000.0,3726.0,66651.0,1
888,E09000022,lambeth,2016-12-01,34670.0,7.35,41335,29,327910.0,175000.0,2725.0,137610.0,1
889,E09000023,lewisham,2016-12-01,32217.0,7.18,34588,18,301867.0,84000.0,3532.0,124357.0,1
890,E09000024,merton,2016-12-01,28224.0,7.62,34199,36,205029.0,94000.0,3762.0,83215.0,1
891,E09000025,newham,2016-12-01,30743.0,7.61,36946,14,340978.0,125000.0,3857.0,110251.0,1
892,E09000026,redbridge,2016-12-01,28237.0,7.57,32190,27,299249.0,94000.0,5644.0,102707.0,1
893,E09000027,richmond upon thames,2016-12-01,33329.0,7.71,38572,42,195846.0,108000.0,5876.0,84294.0,1
894,E09000028,southwark,2016-12-01,37159.0,7.37,42583,34,313223.0,307000.0,2991.0,129740.0,1
895,E09000029,sutton,2016-12-01,28318.0,7.66,34818,37,202220.0,84000.0,4385.0,81628.0,1
896,E09000030,tower hamlets,2016-12-01,45975.0,7.75,64345,28,304854.0,303000.0,2158.0,113185.0,1
897,E09000031,waltham forest,2016-12-01,27455.0,7.67,30172,34,275843.0,86000.0,3881.0,101284.0,1
898,E09000032,wandsworth,2016-12-01,33405.0,7.64,37651,22,316096.0,146000.0,3522.0,141579.0,1
899,E09000033,westminster,2016-12-01,40000.0,7.68,53888,17,247614.0,765000.0,2203.0,122024.0,1
906,E12000007,london,2016-12-01,36170.0,7.54,47924,33,8787892.0,5982000.0,159471.0,3484878.0,0
911,E92000001,england,2016-12-01,28496.0,7.68,35053,44,55268067.0,29972000.0,13303728.0,23732627.0,0
919,E09000002,barking and dagenham,2017-12-01,28553.0,7.66,32093,25,210711.0,66000.0,3780.0,74510.0,1
920,E09000003,barnet,2017-12-01,32143.0,7.63,36818,37,387803.0,176000.0,8675.0,148529.0,1
921,E09000004,bexley,2017-12-01,30733.0,7.42,33857,52,246124.0,91000.0,6429.0,97628.0,1
922,E09000005,brent,2017-12-01,30134.0,7.79,35840,37,329102.0,157000.0,4323.0,118013.0,1
923,E09000006,bromley,2017-12-01,29819.0,7.31,34354,50,329391.0,134000.0,15013.0,138422.0,1
924,E09000007,camden,2017-12-01,38147.0,7.31,44970,30,253361.0,398000.0,2179.0,103826.0,1
925,E09000008,croydon,2017-12-01,32109.0,7.49,35839,38,384837.0,155000.0,8650.0,157394.0,1
926,E09000009,ealing,2017-12-01,30259.0,7.55,36039,49,342736.0,168000.0,5554.0,132094.0,1
927,E09000010,enfield,2017-12-01,29134.0,7.34,34096,36,332705.0,126000.0,8220.0,125369.0,1
928,E09000011,greenwich,2017-12-01,32635.0,7.47,35702,35,282849.0,102000.0,5044.0,110983.0,1

## Dropping duplicates
---

* To remove duplicate rows based on duplication of values in all columns  
  `df.drop_duplicates()`  

* To remove rows that have duplicate entries in a specified column  
  `df.drop_duplicates(subset = ['Make'])`  

* To remove rows that have duplicate entries in multiple columns  
  `df.drop_duplicates(subset = ['Make', 'Model'])` 

* Remove duplicate rows keeping the last instance rather than the first (default):  
  `df.drop_duplicates(keep='last')`

### Exercise 6 - Removing duplicate entries 
---

remove duplicate `area` entries keeping first instance  

**Test output**:  
 Dataframe now contains 50 rows all with date 1999-12-*01*

In [109]:
display(housing_df.drop_duplicates(subset = ["area"]))

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
0,E09000001,city of london,1999-12-01,33020.0,NaN,48922,0,6581.0,NaN,NaN,NaN,1
1,E09000002,barking and dagenham,1999-12-01,21480.0,NaN,23620,3,162444.0,NaN,NaN,NaN,1
2,E09000003,barnet,1999-12-01,19568.0,NaN,23128,8,313469.0,NaN,NaN,NaN,1
3,E09000004,bexley,1999-12-01,18621.0,NaN,21386,18,217458.0,NaN,NaN,NaN,1
4,E09000005,brent,1999-12-01,18532.0,NaN,20911,6,260317.0,NaN,NaN,NaN,1
5,E09000006,bromley,1999-12-01,16720.0,NaN,21293,13,294902.0,NaN,NaN,NaN,1
6,E09000007,camden,1999-12-01,23677.0,NaN,30249,13,190003.0,NaN,NaN,NaN,1
7,E09000008,croydon,1999-12-01,19563.0,NaN,22205,13,332066.0,NaN,NaN,NaN,1
8,E09000009,ealing,1999-12-01,20580.0,NaN,25046,12,302252.0,NaN,NaN,NaN,1
9,E09000010,enfield,1999-12-01,19289.0,NaN,21006,9,272731.0,NaN,NaN,NaN,1
10,E09000011,greenwich,1999-12-01,21236.0,NaN,22263,4,212168.0,NaN,NaN,NaN,1
11,E09000012,hackney,1999-12-01,23249.0,NaN,39629,2,199087.0,NaN,NaN,NaN,1
12,E09000013,hammersmith and fulham,1999-12-01,25000.0,NaN,28555,7,160634.0,NaN,NaN,NaN,1
13,E09000014,haringey,1999-12-01,18783.0,NaN,21683,5,218559.0,NaN,NaN,NaN,1
14,E09000015,harrow,1999-12-01,20596.0,NaN,22824,10,207909.0,NaN,NaN,NaN,1
15,E09000016,havering,1999-12-01,17165.0,NaN,18786,8,225712.0,NaN,NaN,NaN,1
16,E09000017,hillingdon,1999-12-01,24002.0,NaN,28854,11,245053.0,NaN,NaN,NaN,1
17,E09000018,hounslow,1999-12-01,20155.0,NaN,24602,14,214298.0,NaN,NaN,NaN,1
18,E09000019,islington,1999-12-01,25113.0,NaN,34180,2,175717.0,NaN,NaN,NaN,1
19,E09000020,kensington and chelsea,1999-12-01,20646.0,NaN,28074,13,147678.0,NaN,NaN,NaN,1
20,E09000021,kingston upon thames,1999-12-01,19302.0,NaN,22967,18,146003.0,NaN,NaN,NaN,1
21,E09000022,lambeth,1999-12-01,23151.0,NaN,27930,8,266817.0,NaN,NaN,NaN,1
22,E09000023,lewisham,1999-12-01,20580.0,NaN,23283,4,250310.0,NaN,NaN,NaN,1
23,E09000024,merton,1999-12-01,18962.0,NaN,21867,11,185062.0,NaN,NaN,NaN,1
24,E09000025,newham,1999-12-01,18862.0,NaN,20580,3,240517.0,NaN,NaN,NaN,1
25,E09000026,redbridge,1999-12-01,19580.0,NaN,22087,8,238138.0,NaN,NaN,NaN,1
26,E09000027,richmond upon thames,1999-12-01,22321.0,NaN,25832,na,172782.0,NaN,NaN,NaN,1
27,E09000028,southwark,1999-12-01,22784.0,NaN,26994,3,247853.0,NaN,NaN,NaN,1
28,E09000029,sutton,1999-12-01,19582.0,NaN,22725,27,179375.0,NaN,NaN,NaN,1
29,E09000030,tower hamlets,1999-12-01,26376.0,NaN,37524,3,193507.0,NaN,NaN,NaN,1
30,E09000031,waltham forest,1999-12-01,18547.0,NaN,19888,9,221057.0,NaN,NaN,NaN,1
31,E09000032,wandsworth,1999-12-01,21321.0,NaN,24707,7,264220.0,NaN,NaN,NaN,1
32,E09000033,westminster,1999-12-01,24447.0,NaN,36167,7,189233.0,NaN,NaN,NaN,1
33,E12000001,north east,1999-12-01,16282.0,NaN,18351,5,2550314.0,NaN,NaN,NaN,0
34,E12000002,north west,1999-12-01,16977.0,NaN,19609,7,6773115.0,NaN,NaN,NaN,0
35,E12000003,yorkshire and the humber,1999-12-01,16527.0,NaN,18977,7,4956325.0,NaN,NaN,NaN,0
36,E12000004,east midlands,1999-12-01,16392.0,NaN,18864,11,4152443.0,NaN,NaN,NaN,0
37,E12000005,west midlands,1999-12-01,17000.0,NaN,19686,9,5271959.0,NaN,NaN,NaN,0
38,E12000006,east,1999-12-01,18000.0,NaN,20866,14,5338722.0,NaN,NaN,NaN,0
39,E12000007,london,1999-12-01,22487.0,NaN,29640,9,7153912.0,NaN,NaN,NaN,0
40,E12000008,south east,1999-12-01,18737.0,NaN,22361,15,7955124.0,NaN,NaN,NaN,0
41,E12000009,south west,1999-12-01,16727.0,NaN,19203,14,4880958.0,NaN,NaN,NaN,0
42,E13000001,inner london,1999-12-01,NaN,NaN,-,NaN,2750716.0,NaN,NaN,NaN,0
43,E13000002,outer london,1999-12-01,NaN,NaN,-,NaN,4403196.0,NaN,NaN,NaN,0
44,E92000001,england,1999-12-01,17939.0,NaN,21561,10,49032872.0,NaN,NaN,NaN,0
45,K02000001,united kingdom,1999-12-01,17803.0,NaN,21314,NaN,58684427.0,NaN,NaN,NaN,0
46,K03000001,great britain,1999-12-01,17866.0,NaN,21379,NaN,57005421.0,NaN,NaN,NaN,0
47,K04000001,england and wales,1999-12-01,17974.0,NaN,21549,NaN,51933471.0,NaN,NaN,NaN,0
48,N92000002,northern ireland,1999-12-01,15798.0,NaN,19093,NaN,1679006.0,NaN,NaN,NaN,0
49,S92000003,scotland,1999-12-01,16914.0,NaN,19667,NaN,5071950.0,NaN,NaN,NaN,0
50,W92000004,wales,1999-12-01,16457.0,NaN,18486,NaN,2900599.0,NaN,NaN,NaN,0

# Normalising Data  
When we normalise data, we remodel a numeric column in a dataframe to be on a standard scale (e.g. 0 or 1).   

For example if we had a column of BMI scores, we could normalise that column so that all scores greater than or equal to 25 were recoded to the value 1 (bad) and all scores less than 25 were recoded to 0 (good).  

To normalise we need to:
*   write a function, with the dataframe as a parameter, which will look at each row in dataframe column and return either a value in the normalised scale (e.g. 0,1 or 1,2,3,4) depending on that value.

For example:  
```
def normalise_bmi(df):
  if df['bmi'] >= 25:
    return 1
  else:
    return 0

df["bmi"] = df.apply(normalise_bmi, axis=1)
```
This code reassigns the values in the column "bmi" by sending each row one after the other to the normalise_bmi function, which will check the value in the "bmi" column and return either 0 or 1 depending on the value in the "bmi" column.

### Exercise 7 - normalise data set
---

Create a function called **normalise_income(df)** that will return the values 1, 2 or 3 to represent low income, middle income and high income.  If the value in `df['median_salary']` is less than 27441 (the median), return 1, otherwise if it is less than 30932 (the upper quartile) return 2 and otherwise return 3.

Apply the normalise_income(df) function to the `median_salary` column.

*NOTE:  this operation will change the original dataframe so if you run it twice, everything in the median_salary column will change to 1 (as it had already been reduced to 1, 2 or 3 - if this happens, run the code in Exercise 4 again to get the original data again from the file.*

**Test output**:  
The maximum value of the column df['median_salary'] will be 3 and the minimum value will be 1

In [110]:
def normalise_income(df):
    if df['median_salary'] < 27441:
        return 1
    elif df['median_salary'] < 30932:
        return 2
    else:
        return 3

housing_df["median_salary"] = housing_df.apply(normalise_income, axis=1)

# Test
display(housing_df["median_salary"].max())
display(housing_df["median_salary"].min())

3

1

### Exercise 8 - normalise the number of jobs column
---

Using what you have learnt from Exercise 7:  
*  use `df.describe()` to find the median, upper quartile and maximum for the number_of_jobs column  
*  create a function called **normalise_jobs(df)** that will return 1 if the `number_of_jobs` is below the median, 2 if the `number_of_jobs` is below the upper quartile or 3 otherwise.
*  normalise the `number_of_jobs` column by applying the function `normalise_jobs`.

**Test output**:  
The maximum value of the column df['number_of_jobs'] will be 3 and the minimum value will be 1

In [111]:
pd.set_option('display.max_rows', 100)

display(housing_df.describe())

def normalise_jobs(df):
    if df["number_of_jobs"] < 157000:
        return 1
    elif df["number_of_jobs"] < 2217000:
        return 2
    else:
        return 3

housing_df["number_of_jobs"] = housing_df.apply(normalise_jobs, axis=1)

# Test
display(housing_df["number_of_jobs"].max())
display(housing_df["number_of_jobs"].min())

,median_salary,life_satisfaction,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
count,1071.000000,352.000000,1.018000e+03,9.310000e+02,6.660000e+02,6.660000e+02,1071.000000
mean,1.776844,7.485057,6.042576e+06,3.188095e+06,3.724903e+05,8.814682e+05,0.647059
std,0.840375,0.198451,1.526810e+07,8.058302e+06,2.157060e+06,3.690376e+06,0.478108
min,1.000000,7.000000,6.581000e+03,4.700000e+04,3.150000e+02,5.009000e+03,0.000000
25%,1.000000,7.350000,2.243458e+05,9.450000e+04,2.960000e+03,8.763550e+04,0.000000
50%,2.000000,7.510000,2.946035e+05,1.570000e+05,4.323000e+03,1.024020e+05,1.000000
75%,3.000000,7.640000,4.630098e+06,2.217000e+06,8.220000e+03,1.262760e+05,1.000000
max,3.000000,7.960000,6.643555e+07,3.575000e+07,1.330373e+07,2.417217e+07,1.000000

3

1

## Exercise 9 - normalise into a new column
---

Create a new function and code to normalise the `no_of_houses` column BUT this time, instead of assigning the result to `df['no_of_houses']` assign it to a new column called `df['housing_volume']`

**Test output**:  
The maximum value of the column df['housing_volume'] will be 3 and the minimum value will be 1

In [112]:
def normalise_no_of_houses(df):
    if df["no_of_houses"] < 102402:
        return 1
    elif df["no_of_houses"] < 126276:
        return 2
    else:
        return 3

housing_df["housing_volume"] = housing_df.apply(normalise_no_of_houses, axis=1)

# Test
display(housing_df["housing_volume"].max())
display(housing_df["housing_volume"].min())

3

1

### Exercise 10 - normalise boroughs
---

Normalise the `area_size` column so that all values below mean are represented as 0 and otherwise are 1.  Assign the output to a new column called `area_size_normalised`.  

**Test output**:  
`area_size_normalised` column will contain both 0s and 1s.  The position of the first row with value 1 will be 0 and the position of the first row with value 0 will be 102.

In [114]:
def normalise_area_size(df):
    if df["area_size"] < housing_df['area_size'].mean():
        return 0
    else:
        return 1

housing_df["area_size_normalised"] = housing_df.apply(normalise_area_size, axis=1)

# Test
pd.options.display.max_rows = 999
housing_df['area_size_normalised'][0:103]

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
30     1
31     1
32     1
33     1
34     1
35     1
36     1
37     1
38     1
39     1
40     1
41     1
42     1
43     1
44     1
45     1
46     1
47     1
48     1
49     1
50     1
51     1
52     1
53     1
54     1
55     1
56     1
57     1
58     1
59     1
60     1
61     1
62     1
63     1
64     1
65     1
66     1
67     1
68     1
69     1
70     1
71     1
72     1
73     1
74     1
75     1
76     1
77     1
78     1
79     1
80     1
81     1
82     1
83     1
84     1
85     1
86     1
87     1
88     1
89     1
90     1
91     1
92     1
93     1
94     1
95     1
96     1
97     1
98     1
99     1
100    1
101    1
102    0
Name: area_size_normalised, dtype: int64

# Reflection
----

## What skills have you demonstrated in completing this notebook?

Your answer: Ability to sort, clean and normalise data using pandas library functions.

## What caused you the most difficulty?

Your answer: No difficulties.